version: '3'

services: 

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile.prod
    container_name: flask_app_prod
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment: 
      - FLASK_APP=flask/app.py
      - FLASK_ENV=production

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: flask_nginx_prod
    ports: 
      - 8000:80
    depends_on: 
      - flask
